name: App request (GitHub)
description: Request an app on GitHub be added to Universal-DB
labels: ["app request"]
body:
  - type: markdown
    attributes:
      value: "**Please ensure your app complies with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/master/CONTRIBUTING.md#app-requests) before submitting a request.**"
  - type: markdown
    attributes:
      value: "Know how to use git? Consider submitting a pull request instead. See [the wiki](https://github.com/Universal-Team/db/wiki/App-Template) for more information. (this is a hobby project, as simple as it is we don't have time to sit down and review everything all the time. Pull requests will be reviewed much faster)"
  - type: input
    attributes:
      label: GitHub repository of the app
      description: Most metadata will be gathered automatically from the API. Please only include things you actively want to be different.
  - type: input
    attributes:
      label: Title
      description: "The name of the app. (Default: Repository name)"
  - type: input
    attributes:
      label: Author
      description: "The app developer's name(s) (Default: Your GitHub *name*, note that this can be different than your username)"
  - type: input
    attributes:
      label: Short description
      description: "Will be shown on the app cards and in Universal-Updater. (Default: Repository description)"
  - type: dropdown
    attributes:
      label: System(s)
      description: The system(s) the app is native for, so a `.nds` app that works on 3DS is just DS.
      multiple: true
      options:
        - 3DS
        - DS
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Categories
      description: Additional categories can be requested in the other notes.
      multiple: true
      options:
        - Game
        - Emulator
        - App
        - Utility
        - Save Tool
        - FIRM
        - Luma3DS
    validations:
      required: true
  - type: input
    attributes:
      label: Unique ID(s)
      description: The Unique ID(s) of any CIAs of this app, this is the "UniqueId" in the RSF file. If you do not have a 3DS CIA build then skip this.
  - type: input
    attributes:
      label: Image link
      description: For 3DS apps with a 2D banner, that works well.
  - type: input
    attributes:
      label: Icon link
      description: Usually the app icon that's used on the HOME Menu.
  - type: textarea
    attributes:
      label: Long description
      description: You can use HTML and/or Markdown in this, shown on the app's download page.
  - type: textarea
    attributes:
      label: Screenshots
      description: |
        Screenshots of the app to show on the website and in Universal-Updater. Ideally they should be both screens with no separation and nothing extra around them, just 400×480 (for 3DS) or 256×384 (for DS).

        Animated GIFs can be shown on the website, but not in Universal-Updater.
  - type: markdown
    attributes:
      value: |
        **If you've provided a GitHub repository, then only fill out the rest if you want different information than your GitHub repository has.**

        It can all be automatically gathered through the GitHub API.
  - type: input
    attributes:
      label: Website link
      description: If you have a website you want linked
  - type: input
    attributes:
      label: Wiki link
      description: If you have a wiki besides the GitHub wiki (which will be picked up automatically)
  - type: textarea
    attributes:
      label: Other notes
      description: Anything else you want to mention. If the app requires any special steps for installation explain/link an explanation here.
  - type: checkboxes
    attributes:
      label: Developer permission
      description: If you aren't a developer of the app, then please actually check it's alright with them.
      options:
        - label: I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)
          required: true
